export const DEFAULT_REQUEST_DELAY = 1000;

// eslint-disable-next-line max-len
export const TEMP_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDUxMDI0ODYxZGRlNmIyYWMwYTYwNWYiLCJpYXQiOjE2ODYwNDM0OTgsImV4cCI6MTY4NjY0ODI5OH0.ROcjP8vXbAMKWqChd8-82UnmsWSrJeQGMOHnMZf1MfU';
